#!/bin/bash

echo "🚀 Render Deployment Guide"
echo "=========================="
echo ""
echo "Since Render doesn't have a CLI, we'll use the web interface:"
echo ""
echo "1. Go to: https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Configure the service:"
echo "   - Name: football-team-management-backend"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Plan: Free"
echo ""
echo "6. Add Environment Variables:"
echo "   - NODE_ENV: production"
echo "   - PORT: 10000"
echo "   - MONGODB_URI: [Your MongoDB Atlas connection string]"
echo "   - FRONTEND_URL: https://footbball.netlify.app"
echo ""
echo "7. Deploy!"
echo ""
echo "After deployment, you'll get a URL like:"
echo "https://football-team-management-backend.onrender.com"
echo ""
echo "Press Enter when you have your Render backend URL..."
read -r
echo "Great! Now we'll update the frontend to use your backend URL."
