#!/bin/bash

echo "🗄️ MongoDB Atlas Setup Guide"
echo "=============================="
echo ""
echo "1. Go to: https://cloud.mongodb.com/"
echo "2. Sign up for free account"
echo "3. Create a new project"
echo "4. Build a Database → Choose FREE (M0)"
echo "5. Create cluster (takes 3-5 minutes)"
echo ""
echo "6. Database Access:"
echo "   - Add New Database User"
echo "   - Create username/password (SAVE THESE!)"
echo "   - Set privileges to 'Read and write to any database'"
echo ""
echo "7. Network Access:"
echo "   - Add IP Address"
echo "   - Click 'Allow Access from Anywhere' (0.0.0.0/0)"
echo ""
echo "8. Get Connection String:"
echo "   - Database → Connect → Connect your application"
echo "   - Copy the connection string"
echo "   - Replace <password> with your actual password"
echo "   - Replace <dbname> with 'Footballdb'"
echo ""
echo "Example:"
echo "mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/Footballdb?retryWrites=true&w=majority"
echo ""
echo "Press Enter when you have your MongoDB connection string ready..."
read -r
echo "Great! Now we'll proceed with the deployment."
