#!/bin/bash

echo "🗄️ MongoDB Atlas Quick Setup"
echo "============================"
echo ""
echo "1. Go to: https://cloud.mongodb.com/"
echo "2. Sign up/Login with your account"
echo "3. Create a new project (if needed)"
echo "4. Click 'Build a Database'"
echo "5. Choose 'FREE' (M0) tier"
echo "6. Select a region close to you"
echo "7. Create cluster (takes 3-5 minutes)"
echo ""
echo "8. Database Access:"
echo "   - Click 'Database Access'"
echo "   - Click 'Add New Database User'"
echo "   - Choose 'Password' authentication"
echo "   - Create username and password (SAVE THESE!)"
echo "   - Set privileges to 'Read and write to any database'"
echo "   - Click 'Add User'"
echo ""
echo "9. Network Access:"
echo "   - Click 'Network Access'"
echo "   - Click 'Add IP Address'"
echo "   - Click 'Allow Access from Anywhere' (0.0.0.0/0)"
echo "   - Click 'Confirm'"
echo ""
echo "10. Get Connection String:"
echo "    - Click 'Database'"
echo "    - Click 'Connect' on your cluster"
echo "    - Choose 'Connect your application'"
echo "    - Copy the connection string"
echo "    - Replace <password> with your actual password"
echo "    - Replace <dbname> with 'Footballdb'"
echo ""
echo "Example connection string:"
echo "mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/Footballdb?retryWrites=true&w=majority"
echo ""
echo "11. Add to Render Environment Variables:"
echo "    - Go to your Render service dashboard"
echo "    - Click 'Environment' tab"
echo "    - Add MONGODB_URI with your connection string"
echo "    - Add NODE_ENV with value 'production'"
echo "    - Save and redeploy"
echo ""
echo "Press Enter when you have your MongoDB Atlas connection string ready..."
read -r
echo "Great! Now add it to your Render environment variables and redeploy."
